# docker-compose.yml
version: '3'
services:
  # main application
  saqc-config-app:
    container_name: saqc-config-app
    environment:
      # must start and end with slash (`/`)
      - APP_URL=/saqc-config-app/
    build:
      context: .
    ports:
      - "8000:8000"